import type { Pack } from "./types";

export const PACKS: Pack[] = [
  {
    id: "boxing",
    name: "Boxing",
    tagline: "Sweat, gloves, glory",
    description:
      "Sports-magazine cover energy. Gritty single-source lighting, sweat, hand wraps, ring ropes, and the lonely hours in the gym before the lights come up.",
    accentColor: "#e63946",
    style: "photo",
    scenes: [
      "Subject in the corner of a boxing ring under a single overhead spotlight, gloves up at his chin, sweat glistening, dim arena bleachers fading into black behind, dramatic single-source key light, 85mm at f/1.8, Sports Illustrated cover energy.",
      "Subject mid-punch hitting a heavy leather bag in a sun-drenched dusty old-school gym, motion blur on the bag, dust motes catching a beam of light through dirty windows, hand wraps, sleeveless tee, 35mm grainy reportage, ESPN documentary feel.",
      "Subject having his hands wrapped by a coach in a dim locker room before a fight, intense focus on the wraps, single warm tungsten bulb above, fight posters peeling on the wall, 50mm at f/1.4, Caravaggio chiaroscuro.",
      "Subject jumping rope on the cracked-concrete rooftop of a city gym at first light, breath visible in cold air, distant skyline silhouetted by the rising sun, hooded sweatshirt, 85mm telephoto compression, Rocky energy.",
      "Subject doing a roadwork run through misty mountain switchbacks at sunrise, vapor breath, hooded grey sweatshirt, condensation on his face, 24mm wide environmental shot with deep depth-of-field, cinematic.",
      "Subject mid-knockout connecting a clean hook against an opponent in a packed arena ring, ring lights blazing from above, sweat spraying off the impact, motion blur on the punch, 70-200mm sports lens, frozen apex.",
      "Subject at a face-off weigh-in with a rival, foreheads almost touching, the official wedged between them, camera flashes popping in the dark crowd behind, shirtless and dead-eyed, 50mm photojournalism reportage.",
      "Subject in the underdog tunnel walking toward the ring, hood up, posse of cornermen behind, blue-tinted spotlights striping the polished floor, towel slung over the shoulders, 35mm cinematic, HBO 24/7 feel.",
      "Subject working the speed bag in a dimly lit gym, hands a controlled blur, single beam of overhead light pooling on his shoulders, peeling brick walls behind, 100mm at f/2 shallow focus, monochrome film stock.",
      "Subject sitting on the corner stool between rounds, the cutman tending a brow cut with a swab, a coach shouting in his ear, eyes locked dead-ahead, 50mm reportage, Annie Leibovitz portrait energy.",
      "Subject post-fight celebrating with both arms raised, blood beading on the brow, gloves still laced, ring ropes blurred in foreground, confetti drifting down, ecstatic crowd lit only by stadium spotlights, 35mm wide.",
      "Subject shadow-boxing on a misty boardwalk at sunrise, sleeveless hoodie, dramatic golden backlight from a low rising sun, ocean fog rolling in, breath visible, 85mm at f/2 telephoto, magazine-cover composition.",
    ],
    defaultAspectRatio: "3:2",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    tagline: "Headshots that close",
    description:
      "Modern executive headshots — clean, confident, and expensive-looking. Soft window key, restrained palette, magazine-grade clarity. Designed to be your new profile photo.",
    accentColor: "#0a66c2",
    style: "photo",
    scenes: [
      "Subject in a charcoal tailored blazer over a crisp white shirt, no tie, soft north-window key light, neutral grey paper backdrop, slight forward lean toward camera, calm direct gaze, subtle confident smile, 85mm at f/2.8, classic head-and-shoulders LinkedIn crop.",
      "Subject in a navy turtleneck against a textured off-white plaster wall, single soft beauty-dish key from camera-left, deep shadow on the off-side, three-quarter angle, slight head tilt, tech-founder portrait, 100mm at f/2.",
      "Subject leaning on a glass-walled boardroom table at golden hour, sleeves of a pale-blue oxford shirt rolled to the forearm, soft window backlight rimming the shoulders, downtown skyline soft-blurred behind, mid-laugh candid, 50mm at f/1.8.",
      "Subject seated in a leather Eames chair in a minimalist office, soft north-window light pouring across one side of the face, hands loosely folded, slight forward lean, Forbes-cover gravitas, medium-format colour negative look, 85mm.",
      "Subject in head-to-toe black knit on a black backdrop, only the face emerging into a single small key light, austere minimalist tech-icon homage, direct eye contact with camera, 100mm at f/2.8 portrait.",
      "Subject standing in front of a clean cyclorama in cream chunky-knit sweater, soft umbrella key plus a faint warm rim, hands relaxed at sides, body angled, friendly direct smile, 85mm modern-creative-director portrait.",
      "Subject mid-conversation across a café table at a brushed-steel espresso bar, half-laughing at someone off-camera, warm tungsten ambient, candid 35mm reportage, magazine-style executive profile.",
      "Subject in a navy three-piece suit standing against a deep-burgundy textured wall, single soft Rembrandt key from camera-right, hands in pockets, three-quarter pose, GQ-style power portrait, 100mm at f/2.8.",
      "Subject in a relaxed grey crewneck against a soft warm-grey backdrop, ringlight key with a faint kicker rim, head and shoulders, gentle Mona Lisa half-smile, 100mm beauty-clean portrait, perfect catchlights in the eyes.",
      "Subject seated on a wooden bench inside an architectural glass atrium, sleeves rolled, hands clasped, dappled afternoon sun crossing the chest, slight head turn toward camera, 50mm environmental editorial portrait.",
      "Subject standing on stage post-keynote with a slim wireless mic in hand, single hard top-light, audience silhouettes blurred far behind, mid-gesture, confident open expression, Sony Venice 2 + 50mm cinematic look.",
      "Subject at a reclaimed-wood standing desk in a sunlit loft office, mid-stride mid-thought, looking just past camera, soft window backlight, slate-blue button-up sleeves rolled, 35mm at f/2 candid environmental headshot.",
    ],
    defaultAspectRatio: "1:1",
  },
  {
    id: "cinematic",
    name: "Cinematic",
    tagline: "A film you haven't seen yet",
    description:
      "Anamorphic flares, Wong Kar-wai neon, Roger Deakins sun. Every frame looks like a still from a movie that never got made.",
    accentColor: "#d97757",
    scenes: [
      "Subject standing alone on a rain-slicked Hong Kong alley at 2am, neon signage reflecting in puddles, anamorphic 2.39:1 framing, Kodak Vision3 500T grain, warm-cool colour split.",
      "Subject silhouetted against a vast desert horizon at golden hour, single backlight kissing dust in the air, ARRI Alexa LF, 40mm Cooke, Roger Deakins palette.",
      "Subject leaning out of a moving 1970s sedan, motion-blurred Tokyo expressway lights streaking past, side-window reflection, 35mm grainy stock, telephoto compression.",
      "Subject in profile inside a dim diner booth, single tungsten pendant overhead, condensation on the window, half-eaten pie, 50mm at f/1.4, Edward Hopper composition.",
      "Subject mid-laugh in the back of a yellow cab, sodium streetlight strobing across face, hand-held 16mm look, faded Kodak Gold, late 90s indie film texture.",
      "Subject walking away from a burning car wreck on an empty highway at dusk, smoke rising, deep teal sky, no expression, anamorphic flare across frame, IMAX wide.",
      "Subject standing in waist-deep ocean at twilight, holding a single match, water mirror-still, faintest violet horizon, large-format colour negative, no other light source.",
      "Subject sitting on a hotel bed in a robe, faced away from a flickering CRT TV, RGB cast across shoulders, dust-mote light beam from window, 35mm Cinemascope.",
      "Subject mid-stride through a foggy Eastern European train station at dawn, long wool coat, breath visible, low-angle hero shot, ARRI Master Prime 32mm.",
      "Subject framed through a doorway from another room, conversation cut-off, soft incandescent kitchen light pooling around them, voyeuristic mid-distance, 75mm anamorphic.",
      "Subject under a single overhead interrogation lamp, surrounding pure black, sweat beading, jaw tight, hard top light only, large-format monochrome.",
      "Subject riding a motorbike across the salt flats at midday, white sky white ground, helmet off, scarf trailing, drone-style wide-shot lens compression, washed Kodachrome.",
    ],
    defaultAspectRatio: "16:9",
  },
  {
    id: "tech-founder",
    name: "Tech Founder",
    tagline: "Series-A polish",
    description:
      "Boardrooms, podcasts, on-stage keynotes, code-lit faces. Built for press kits and conference deck headers.",
    accentColor: "#5b8def",
    scenes: [
      "Subject mid-keynote on a black stage, single key light from above, audience in soft silhouette, holding a slim wireless mic, shot on Sony Venice 2 with 50mm at f/2.",
      "Subject in a glass-walled boardroom at golden hour, sleeves rolled, mid-gesture explaining a whiteboard diagram, soft window backlight, 35mm.",
      "Subject leaning into a podcast mic in a sound-treated studio, headphones on, warm tungsten key, deep shadow on the off-side, 85mm portrait lens.",
      "Subject reviewing terminal output at a standing desk, RGB monitor glow on face, dark office, nighttime city skyline blur in background, 50mm at f/1.4.",
      "Subject in a knit and chinos against a clean cyclorama, soft beauty-dish key, slight smile, eyes to camera, classic LinkedIn-quality 85mm headshot.",
      "Subject walking through a server room, blue indicator lights striping the face, hand brushing a rack, 24mm wide environmental shot.",
      "Subject seated for a Forbes-style portrait in a leather Eames chair, soft north-window light, hands folded, slight forward lean, medium-format colour neg.",
      "Subject demoing a product to a small huddle of engineers around a laptop, paper cups, tense joy on faces, available-light office, 35mm photojournalism.",
      "Subject in head-to-toe matte black turtleneck against a black backdrop, single hard key from camera-left, austere minimalist tech-icon homage, 100mm macro.",
      "Subject signing paperwork at a marble conference table, sharp suit, golden afternoon backlight through floor-to-ceiling windows, motion of pen, 50mm.",
      "Subject in jeans and tee at a hackathon, energy-drink cans, sticker-covered laptop, fluorescent overhead, candid 28mm reportage with mild flash.",
      "Subject standing in front of a Y-Combinator-style orange wall holding a sharpie and laughing, square 6x6 format, ringlight key, on-axis editorial.",
    ],
    defaultAspectRatio: "3:2",
  },
  {
    id: "editorial",
    name: "Editorial",
    tagline: "Vogue Italia, page seventeen",
    description:
      "High-fashion stylings. Hard light, prop-heavy, oversized silhouettes. Made for portfolios and tear-sheets.",
    accentColor: "#e8b4a0",
    scenes: [
      "Subject in an oversized tailored suit against a seamless cyclorama, hard ringlight key, hands in pockets, asymmetric pose, Vogue Italia April issue.",
      "Subject draped over an antique velvet chaise, single window of north light, oversized pearl earring, eyes closed, large-format 4x5 colour transparency.",
      "Subject submerged to the collarbone in a porcelain bathtub of milk, single overhead softbox, hair slicked back, perfect symmetry, beauty-editorial 100mm macro.",
      "Subject in front of a seven-foot-tall wall of fresh roses, monochrome scarlet wardrobe blending with backdrop, ringlight key, head tilt, 80mm Mamiya.",
      "Subject standing in two feet of sand inside a white-walled gallery, wind machine, dishevelled couture, hard daylight strobe, conceptual editorial 50mm.",
      "Subject seated on a wooden chair in a flooded warehouse, ankle-deep water reflecting them, single industrial pendant lamp, moody editorial 35mm anamorphic.",
      "Subject lying on grass in Marie Antoinette pastel couture, scattered macarons, drone overhead flat-lay, midday sun, hyper-saturated kodachrome.",
      "Subject mid-twirl in a backless emerald gown on a black stage, ring of LED tubes around them, slow-shutter motion blur, 35mm with strobe second-curtain sync.",
      "Subject framed inside a doorway of a brutalist concrete monolith, monochrome charcoal wardrobe, harsh midday top-light, full-body hero shot, 24mm.",
      "Subject behind a sheer organza curtain backlit by a single hard daylight strobe, profile silhouette emerging, breath-on-glass softness, 85mm.",
      "Subject in a translucent latex outfit standing in front of a mirrored wall, soft pink gel uplight, distorted reflections, 50mm conceptual fashion.",
      "Subject up to the waist in a wheat field at dusk, oversized vintage trench coat, single rim of golden hour, painterly composition, Pentax 67 medium-format.",
    ],
    defaultAspectRatio: "2:3",
  },
  {
    id: "streetwear",
    name: "Streetwear",
    tagline: "Off-the-clock heat check",
    description:
      "Tokyo back streets, NYC SoHo, Berlin courtyards. Layered fits, real environments, casual swagger.",
    accentColor: "#222222",
    scenes: [
      "Subject leaning on a graffitied wall in Shibuya at golden hour, hooded windbreaker, layered chains, 35mm street photography Fuji X-Pro look.",
      "Subject mid-crossing a SoHo intersection at lunchtime, oversized denim, taxi blur in background, candid photojournalism 28mm.",
      "Subject sitting on a skate ramp in a Berlin courtyard, sneakers off-frame, brutalist concrete walls, overcast soft light, environmental 24mm wide.",
      "Subject standing under a Hong Kong neon sign at night, puffer jacket, cigarette smoke not visible, ambient mixed-source colour, 50mm cinematic.",
      "Subject crouched in front of a mirror-tile bodega wall at dusk, fully layered fit-check pose, fluorescent sign overhead casting cyan, ringflash for face, 35mm.",
      "Subject mid-jump on a Brooklyn rooftop at sunrise, fitted cap, layered tee plus tech-fleece, motion frozen by strobe, 24mm wide hero shot.",
      "Subject leaning against a vintage Mercedes sedan in a London mews, balaclava optional, fog, drizzle on bodywork, 85mm telephoto compression.",
      "Subject sitting on subway platform bench at 11pm, headphones on, train motion-blurred behind, sodium fluorescents, 35mm grainy reportage.",
      "Subject framed against a Tokyo vending-machine wall, single can in hand, harsh top fluorescents, Fuji 400H Pro film stock, 50mm portrait crop.",
      "Subject jaywalking across a Paris cobblestone street at blue hour, tailored grey wool overcoat, camera caught mid-stride, 35mm street-cinema look.",
      "Subject sitting on the curb beside a graffiti-covered freight container, eating dollar pizza, harsh midday flat sun, 28mm photo-essay framing.",
      "Subject standing in front of a stack of crushed Coke crates in a Mexico City alley, oversized jersey, single overhead bulb, gritty 35mm flash on-camera.",
    ],
    defaultAspectRatio: "3:2",
  },
  {
    id: "travel",
    name: "Travel",
    tagline: "Postcards you can't fake",
    description:
      "Iconic locations, real-world scale, atmospheric weather. Memory pieces from places worth flying to.",
    accentColor: "#f5a623",
    scenes: [
      "Subject on a Greek island clifftop at sunset, white linen, wind-tangled hair, wide drone-style 35mm with telephoto compression, Aegean blue beneath.",
      "Subject standing on the prow of a longtail boat threading limestone karsts in Phang Nga bay at dawn, mist on water, 50mm soft-light portrait.",
      "Subject reading a paperback in a Marrakech riad courtyard, mosaic tile, pomegranate tree dappled shade, mint tea on copper tray, 35mm warm tone.",
      "Subject hiking a basalt ridge in Iceland under low storm clouds, breath visible, bright red shell jacket against grey, 24mm environmental wide.",
      "Subject sitting in the back of a tuk-tuk through neon Bangkok at midnight, motion-blur lights streaking, Fujifilm Pro 400H, 35mm.",
      "Subject swimming in a hidden Mexican cenote, sun shaft piercing the cave water, viewed half-above-half-below the surface, 16mm fisheye, Aquatech housing.",
      "Subject leaning on the rail of a Venetian water taxi at golden hour, pastel buildings receding, 85mm soft portrait, Kodak Ektar.",
      "Subject standing alone on Bolivian salt flats at midday, mirror sky-water reflection, oversized brimmed hat, full-body wide 24mm with deep depth-of-field.",
      "Subject sipping espresso at a Roman cafe table on cobblestone, Vespa parked behind, low afternoon raking light, 50mm Leica candid.",
      "Subject paragliding above the Cappadocia balloon fleet at dawn, harness visible, hot-air balloons polka-dotting valley below, 14mm GoPro POV style.",
      "Subject riding a sleeper-train carriage at first light, condensation on the window, Trans-Siberian wood-panel interior, 35mm available light.",
      "Subject crouched in temple courtyard in Kyoto autumn, maple leaves falling, charcoal kimono, raked-gravel pattern, 85mm telephoto bokeh.",
    ],
    defaultAspectRatio: "16:9",
  },
  {
    id: "dark-academia",
    name: "Dark Academia",
    tagline: "Tweed, candlelight, secret society",
    description:
      "Bodleian libraries, ivy walls, leather-bound stacks. Caravaggio shadows and Latin engravings.",
    accentColor: "#7a5230",
    scenes: [
      "Subject reading by candlelight at a long oak refectory table, Bodleian-style stacks behind, single flame as only light source, 50mm at f/1.4 Caravaggio chiaroscuro.",
      "Subject in tweed and wire-frame glasses on a moss-covered stone bridge, ivy archway, autumn fog, 35mm soft pictorialist look, hand-tinted feel.",
      "Subject sitting cross-legged in a ladder-lined private library, leather chesterfield, hot tea steaming, north window soft light, 35mm Kodak Portra.",
      "Subject mid-stride down a cloister of pointed Gothic arches at dusk, woollen scarf trailing, blue-hour ambient, 24mm wide environmental.",
      "Subject in a cathedral nave looking up at stained-glass rose window, beams of coloured light striping face, full-body wide 28mm large format.",
      "Subject hunched over a spread of antique maps and brass dividers, single green banker's lamp, deep brown shadow elsewhere, 85mm tabletop documentary.",
      "Subject walking ivy-covered college quad in soft snowfall, breath visible, slight smile, navy peacoat, 35mm bokeh portrait.",
      "Subject lecturing from behind a wooden lectern in an empty hall, gestural mid-sentence, dust motes in window beam, monochrome large-format Tri-X.",
      "Subject lying on grass with an open volume of Ovid, fountain in background, dappled cloister sun, overhead 50mm flat-lay portrait.",
      "Subject by a bay window at twilight, vintage globe and barometer on sill, melancholy half-profile, single soft window key, 85mm Rembrandt lighting.",
      "Subject in a candlelit secret-society chamber, brass astrolabe in hand, hood half drawn, single warm taper as key light, 50mm large-format moody.",
      "Subject pacing a chalkboard-covered seminar room, equations behind in white chalk, sleeves rolled, 35mm ambient overhead fluorescents.",
    ],
    defaultAspectRatio: "2:3",
  },
  {
    id: "y2k",
    name: "Y2K",
    tagline: "2003 had heat",
    description:
      "Chrome reflections, frosted plastic, flip-phones, on-camera flash. Sidekick-era nostalgia, glossy.",
    accentColor: "#e8c1ff",
    scenes: [
      "Subject in low-rise jeans and tinted purple sunglasses against a chrome reflective backdrop, direct on-camera flash, 50mm 2003 magazine spread.",
      "Subject seated cross-legged on an inflatable plastic chair in a candy-pink bedroom, flip phone in hand, glittery eyeshadow, 35mm flash photography.",
      "Subject in a velour tracksuit holding a tiny rhinestone dog, mall food court behind, fluorescent ceiling, snapshot 28mm flash on-camera.",
      "Subject leaning against a chrome SUV in a strip-mall parking lot at dusk, frosted-tip hair, oversized white belt, ringflash, late-90s photo-shoot energy.",
      "Subject in a metallic silver puffer crouched on a sidewalk grate, breath visible, MTV-2002 hip-hop video framing, fisheye 16mm.",
      "Subject mid-pose on a backlit transparent acrylic chair, frosted plastic everywhere, hot pink and lime gels, 50mm beauty-editorial flash.",
      "Subject at an arcade DDR machine, motion frozen mid-step, neon screen glow on face, deep arcade darkness behind, 24mm strobe-frozen.",
      "Subject sprawled across a beanbag in front of a CRT TV showing static, glow-in-the-dark stars on ceiling, on-camera bounce flash, 35mm.",
      "Subject in butterfly clips and lip gloss for a passport-photo-style three-shot strip, blue paper backdrop, harsh booth flash, 50mm.",
      "Subject sitting on a yellow Vespa with a very early Sidekick phone, suburban driveway, harsh midday flash, 35mm snapshot.",
      "Subject on a webcam-style square crop, MSN messenger pixel-noise feel, magenta gel rim light, frosted window behind, 85mm.",
      "Subject spinning a translucent yo-yo in a roller rink, disco ball spangles on face, motion-blur skates, 35mm slow-shutter strobe sync.",
    ],
    defaultAspectRatio: "1:1",
  },
  {
    id: "anime-convention",
    name: "Anime Con",
    tagline: "Akihabara at dusk",
    description:
      "Cosplay backdrops, expo crowds, cherry blossoms, neon arcades. Convention floor energy, lovingly composed.",
    accentColor: "#ff6fa3",
    scenes: [
      "Subject under cherry blossoms in Akihabara at dusk, paper lanterns overhead, soft pink ambient, Fujifilm Pro 400H, 50mm shallow depth of field.",
      "Subject inside a neon-soaked Tokyo arcade, mech-game cabinet behind, magenta-cyan reflections on face, 35mm grainy ambient.",
      "Subject mid-pose on a convention-floor staircase, expo banners blurred behind, flash on-camera, 28mm crowd-energy reportage.",
      "Subject framed by a torii gate at twilight, ghibli-soft sky, paper crane in hand, 85mm portrait, dreamy backlight.",
      "Subject sitting on a curb outside the venue eating melon-pan, lanyard heavy with badges, candid 35mm Kodak Gold.",
      "Subject in a maid-cafe interior, pastel pink booth, parfait on table, soft fairy-light bokeh, 50mm at f/1.8.",
      "Subject silhouetted on a rooftop overlook of Shinjuku at night, kanji billboards alive, wind-blown hair, 35mm long exposure with hand-held drag.",
      "Subject browsing a wall of figure-collectibles under harsh fluorescents, fish-eye 8mm wide for the maximalist shelf-scape feel.",
      "Subject riding the Yamanote line late at night, train interior empty, flickering overhead, 35mm tungsten balance with grain.",
      "Subject crouched at street level in Akihabara in the rain, umbrella translucent, signage reflected in puddle, 50mm cinematic anamorphic flare.",
      "Subject on a convention-floor stage holding a microphone, spotlight cone in haze, audience phones glittering, 85mm long lens.",
      "Subject leaning over a glass display case of vintage Famicom cartridges, single LED case-light up-lighting face, macro 100mm shallow focus.",
    ],
    defaultAspectRatio: "2:3",
  },
  {
    id: "album-cover",
    name: "Album Cover",
    tagline: "Type-friendly. Iconic.",
    description:
      "Bold conceptual compositions with negative space for type. Made to print at 12x12 and stop scrolls.",
    accentColor: "#000000",
    scenes: [
      "Subject submerged to the chin in milk, white tile background, overhead fluorescents, perfect axial symmetry, 1:1 square format, ample negative space above.",
      "Subject standing dead-centre in an empty desert, hard midday top-light, white horizon, full-body wide 24mm, type-area sky.",
      "Subject silhouetted against a single column of red gel light in a black room, head turned three-quarter, 50mm minimalist, square crop.",
      "Subject kneeling on white seamless paper, hood up, fully shadowed face, single hard kicker rim only, 85mm conceptual portrait.",
      "Subject's hand emerging from black water holding a single matchstick, rest of frame pure black, 100mm macro, perfect square 1:1.",
      "Subject submerged in a transparent acrylic box of fog, profile only just legible, single side-light, 50mm large-format conceptual.",
      "Subject lying on bare concrete floor flat-lay overhead shot, arms outstretched, single overhead pendant casting hard shadow, 1:1 square.",
      "Subject behind a sheet of cracked safety glass, only one eye visible through a clear pane, hard side-light, 100mm macro.",
      "Subject framed by an oversized vintage paper-cone diffuser, single hot-bulb backlight, monochrome high-key, 50mm large-format.",
      "Subject in a fully red-painted room wearing matching red wardrobe, eyes alone breaking the colour, 85mm beauty editorial.",
      "Subject standing on a roof with helicopter spotlight beam striping them from above, mid-frame, deep blue sky, 35mm ARRI cinematic.",
      "Subject viewed from below on a Plexiglas floor, soles of bare feet pressing the surface, full-body distortion, hard top-light, 14mm.",
    ],
    defaultAspectRatio: "1:1",
  },
  {
    id: "magazine-cover",
    name: "Magazine Cover",
    tagline: "Masthead-ready, eye-contact, tight crop",
    description:
      "Vogue, Time, GQ-style framing. Negative space at the top for masthead, locked eye contact, signature lighting.",
    accentColor: "#c0392b",
    scenes: [
      "Subject head-and-shoulders eye-contact portrait against muted seamless backdrop, soft-box key plus warm rim, generous space above for masthead, 85mm at f/2.",
      "Subject in a tailored turtleneck against deep navy, hard ring-light, jaw set, slight head-tilt, 100mm Vogue-cover crop.",
      "Subject in motion mid-laugh, head thrown slightly back, paper-textured backdrop, beauty-dish key, 85mm energetic candid cover.",
      "Subject wrapped in a chunky knit, oversized collar framing face, pale grey backdrop, north-window soft, 100mm GQ-cover crop.",
      "Subject seated on stool against a blood-red cyclorama, arms folded, direct gaze, hard sun-equivalent strobe, 85mm Time-cover gravitas.",
      "Subject in profile against a textured plaster wall, single Rembrandt key, wisp of hair across cheek, 100mm classic Vanity Fair feel.",
      "Subject wet-look hair, off-shoulder garment, mist of water on skin, blue-grey backdrop, ringlight, 85mm beauty-cover crop.",
      "Subject staring through a sheer black scrim, surreal cover concept, single high-key strobe, 100mm conceptual editorial.",
      "Subject mid-gesture in tailored suit jacket open over bare collarbone, against burnt-orange paper, 85mm power-portrait.",
      "Subject in oversized vintage spectacles, soft beauty light, paper backdrop in pale blush, 100mm intimate cover crop.",
      "Subject framed by a halo of neon tube ring, all face beautifully lit, deep black behind, 85mm contemporary cover style.",
      "Subject in head-to-toe black against black, only face emerging into light, single small key light, 100mm Avedon-homage cover.",
    ],
    defaultAspectRatio: "2:3",
  },
  {
    id: "dating-profile",
    name: "Dating Profile",
    tagline: "Quietly rich, effortlessly aesthetic",
    description:
      "Old-money meets new-money on the apps. Yacht in Capri, espresso in Milan, Porsche keys on the kitchen island, perfectly tailored linen. Charming, never thirsty, never trying.",
    accentColor: "#c9a86a",
    scenes: [
      "Subject on the bow of a sleek white yacht anchored off the Amalfi coast at golden hour, unbuttoned cream linen shirt, tan, gold watch glinting, holding a glass of champagne, turquoise water and pastel cliffside town behind, 35mm cinematic, soft warm backlight, magazine-grade.",
      "Subject at an espresso bar in Milan, marble counter, perfectly cut navy tailored jacket over a white tee, leaning on the counter mid-laugh holding a tiny cup, soft morning window light, 50mm at f/2, candid editorial.",
      "Subject driving a vintage open-top Porsche along a coastal road at sunset, one hand on the wheel, sunglasses, white tee, hair in the wind, palm trees and ocean blurred behind, 35mm cinematic golden hour, telephoto compression.",
      "Subject in a tailored tuxedo at a black-tie event, slightly loosened bow tie, sharing a private laugh with someone off-camera, champagne in hand, blurred chandelier bokeh behind, 85mm at f/1.8, classic Vanity Fair aesthetic.",
      "Subject on a private rooftop terrace overlooking the Manhattan skyline at blue hour, charcoal cashmere overcoat over a black turtleneck, holding a heavy crystal whiskey glass, city lights in the background, 50mm cinematic, dramatic ambient.",
      "Subject in a perfectly tailored suit walking out of a Bemelmans-style hotel bar, slight smile, doorman blurred behind, slick rain on the sidewalk reflecting neon, 35mm street-cinema, telephoto compression at dusk.",
      "Subject in a chef's apron at a marble kitchen island in a beautiful brownstone, plating a course with tweezers, golden retriever looking up at him, wine bottle on the counter, soft golden window light, 35mm candid lifestyle.",
      "Subject reading the FT in a velvet armchair of a private members' club library, leather-bound books on the wall behind, espresso and pocket square on the side table, single warm window light, 50mm at f/2.",
      "Subject on horseback at golden hour in the Tuscan countryside, riding boots and a chambray shirt, cypress trees and rolling hills, telephoto 200mm with rim light, painterly cinematic composition.",
      "Subject post-workout in a high-end private gym, towel around the neck, fitted black training tee revealing a defined athletic build, gold chain, holding a glass bottle of water, soft cool morning light, 50mm editorial.",
      "Subject at the helm of a vintage sailboat at sunset, deck shoes, white linen rolled to the elbows, sun-tanned, slight wind in the hair, ocean horizon glowing pink and orange, 35mm cinematic, warm backlight.",
      "Subject on a snowy chalet balcony at dusk in St. Moritz, cream cable-knit roll-neck and tailored wool trousers, mug of mulled wine in gloved hands, mountain ski resort lights twinkling behind, 50mm warm ambient, magazine-grade.",
    ],
    defaultAspectRatio: "3:2",
  },
];

export function getPack(id: string): Pack | null {
  return PACKS.find((p) => p.id === id) ?? null;
}
