import type { Pack } from "./types";

export const PACKS: Pack[] = [
  {
    id: "gta",
    name: "GTA 6",
    tagline: "Welcome to Leonida",
    description:
      "GTA 6 promotional cover artwork. Hyper-detailed painterly digital illustration, cinematic rim lighting, vibrant neon-Miami palette, dramatic Vice City sunset.",
    accentColor: "#ff5fb4",
    style: "illustration",
    scenes: [
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, dramatic cinematic lighting, rim light glow, vibrant neon Miami palette, atmospheric haze, trending on ArtStation, 8K detail. Subject leaning on the bonnet of a red sports car at a Vice City beachfront sunset, palm-tree silhouettes, gold chain over white tank top, gritty hero composition, full body shot.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, neon Miami night palette, magenta and cyan rim lighting, atmospheric rain mist, trending on ArtStation, 8K. Subject in a leather jacket on a wet Vice City street, police lights flashing in the distance, downtown skyline behind, dramatic noir hero composition, full body shot.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, golden-hour Vice City palette with palm trees in silhouette, cinematic rim light, trending on ArtStation, 8K. Subject in a sharp black suit standing beside a black luxury sedan in front of downtown Vice City, oversized aviators, full body shot, dramatic hero composition.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, vibrant pastel-and-neon Miami sunset palette, cinematic backlight, atmospheric haze, trending on ArtStation, 8K detail. Subject leaning on a white convertible at the boardwalk, palm trees lining the strip, open Hawaiian shirt, full body shot, dramatic comic book cover composition.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, neon-soaked Miami night, electric magenta and cyan ambient, cinematic rim light, trending on ArtStation, 8K. Subject standing on a Vice City club rooftop at midnight, glittering downtown skyline behind, holding a martini, neon backlight haloing the silhouette, full body shot, dramatic hero composition.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, golden-hour Florida swamp palette, cinematic dappled light through cypress trees, atmospheric haze, trending on ArtStation, 8K. Subject standing on the bow of an airboat gliding through the Leonida Everglades, denim and a sleeveless shirt, dramatic hero composition, full body shot.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, neon Vice City night with chrome reflections, magenta-cyan rim lighting, atmospheric mist, trending on ArtStation, 8K. Subject straddling a chrome sport bike in front of an Art Deco hotel facade, leather jacket, helmet under one arm, dramatic comic book cover composition, full body shot.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, vibrant Miami beachfront daylight, cinematic rim light from above, atmospheric haze, trending on ArtStation, 8K. Subject mid-stride on the Vice Beach boardwalk, hands in pockets, lifeguard tower and palm trees behind, gritty hero composition, full body shot.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, neon Miami strip-club exterior at midnight, electric pink and purple rim lighting, atmospheric smoke, trending on ArtStation, 8K. Subject standing under the glow of a neon palm-tree sign outside a Vice City nightclub, gold chain, leather, dramatic hero composition, full body shot.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, hazy gold Florida coastline palette, cinematic backlight from a low sun, trending on ArtStation, 8K. Subject on the deck of a white speedboat tearing across turquoise Leonida Keys waters, ocean spray, open shirt and gold chain, dramatic action composition, full body shot.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, sunset trailer-park Florida palette, golden cinematic rim light, atmospheric haze, trending on ArtStation, 8K. Subject leaning on a beat-up muscle car in a Leonida trailer-park lot, sunset behind, sleeveless shirt and tattoos, dramatic hero composition, full body shot.",
      "GTA 6 promotional cover art, hyper-detailed painterly digital illustration in the style of Rockstar Games loading screens, vibrant Vice City golf-course palette, cinematic golden-hour light, trending on ArtStation, 8K. Subject on a luxury Vice City rooftop pool deck overlooking neon-lit downtown at dusk, holding a champagne flute, palm trees, dramatic hero composition, full body shot.",
    ],
    defaultAspectRatio: "4:3",
  },
  {
    id: "yellow-town",
    name: "Yellow Town",
    tagline: "Resident of a fictional cartoon town",
    description:
      "Classic 1990s American yellow-skin animated sitcom look. Hand-drawn 2D cels, four-fingered characters with big round white eyes and overbite, bold black outlines, flat primary-colour palette. Cameos by every familiar small-town archetype.",
    accentColor: "#ffd521",
    style: "illustration",
    scenes: [
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters with big round white eyes, small black pupils and overbite, bold black outlines, flat saturated primary-colour palette. Subject sitting on a long sagging orange family-room couch in front of a small CRT TV, surrounded by a yellow-skinned cartoon family — a balding overweight father in a white shirt and blue trousers, a tall blue-beehive-haired mother in a green dress, a spiky-haired troublemaker boy in an orange tee and a studious little girl with a saxophone — wood-panel walls and brown carpet, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes with overbite, bold black outlines, flat saturated colours. Subject sitting at the bar of a dim yellow-skinned cartoon dive bar across from a grumpy short hook-nosed bartender pouring a frosted mug of foamy yellow cartoon lager, neon generic beer sign behind, two yellow-skinned bar regulars slumped on neighbouring stools, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject in a white safety hard hat at a control-panel desk inside a yellow-skinned cartoon nuclear power plant, an ancient skeletal billionaire cartoon boss in a brown suit hunched behind with hands tented and eyes narrowed, his fawning bespectacled grey-haired assistant standing beside him, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject at the counter of a yellow-skinned cartoon fast-food restaurant being handed a clown-branded meal box by a green-haired cartoon clown TV host with a frilly white collar and red bow tie, red-and-yellow clown mascot signage behind, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject at the counter of a yellow-skinned cartoon convenience store buying a giant blue frozen slushy drink from a tall thin black-haired moustached cartoon clerk in a white shirt and red tie, fluorescent ceiling lights, snack racks and slushy machine behind, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject sitting in the front seat of a yellow school bus next to a scruffy long-haired cartoon bus driver in a baseball cap with a relaxed grin, suburban houses streaking past the window, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject standing in front of a yellow-skinned cartoon donut shop with a giant smiling cartoon-boy mascot statue holding an oversized pink-frosted donut on the roof, generic suburban commercial strip, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject sitting in a yellow-skinned cartoon school principal's office across the desk from a balding bespectacled principal with a tall comb-over in a brown suit, an American flag and a chalkboard behind, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject playing tabletop chess at a wooden picnic table in a yellow-skinned cartoon municipal park beneath a single oak tree with a bespectacled blue-haired cartoon kid in a striped shirt, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject standing at the front desk of a yellow-skinned cartoon small-town police station with a rotund moustached cartoon police chief in a blue uniform leaning on the counter eating a pink-frosted sprinkled donut, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject standing in a cluttered yellow-skinned cartoon comic-book store, a morbidly obese ponytailed cartoon shopkeeper with a goatee in a tight graphic tee behind the counter, walls of comics and figurines, full body cartoon scene.",
      "Classic 1990s American yellow-skinned animated sitcom cartoon, hand-drawn 2D animation cel, four-fingered cartoon characters, big round white eyes, bold black outlines, flat saturated colours. Subject standing on the front lawn of a pink two-story suburban cartoon family house at sunset, a kindly mustached cartoon neighbour in a green sweater and round glasses leaning over the picket fence with a wave and a grin, sprinkler arcing water on the green lawn, full body cartoon scene.",
    ],
    defaultAspectRatio: "4:3",
  },
  {
    id: "cinematic",
    name: "Cinematic",
    tagline: "A film you haven't seen yet",
    description:
      "Anamorphic flares, Wong Kar-wai neon, Roger Deakins sun. Every frame looks like a still from a movie that never got made.",
    accentColor: "#d97757",
    scenes: [
      "Subject standing alone on a rain-slicked Hong Kong alley at 2am, neon signage reflecting in puddles, anamorphic 2.39:1 framing, Kodak Vision3 500T grain, warm-cool colour split.",
      "Subject silhouetted against a vast desert horizon at golden hour, single backlight kissing dust in the air, ARRI Alexa LF, 40mm Cooke, Roger Deakins palette.",
      "Subject leaning out of a moving 1970s sedan, motion-blurred Tokyo expressway lights streaking past, side-window reflection, 35mm grainy stock, telephoto compression.",
      "Subject in profile inside a dim diner booth, single tungsten pendant overhead, condensation on the window, half-eaten pie, 50mm at f/1.4, Edward Hopper composition.",
      "Subject mid-laugh in the back of a yellow cab, sodium streetlight strobing across face, hand-held 16mm look, faded Kodak Gold, late 90s indie film texture.",
      "Subject walking away from a burning car wreck on an empty highway at dusk, smoke rising, deep teal sky, no expression, anamorphic flare across frame, IMAX wide.",
      "Subject standing in waist-deep ocean at twilight, holding a single match, water mirror-still, faintest violet horizon, large-format colour negative, no other light source.",
      "Subject sitting on a hotel bed in a robe, faced away from a flickering CRT TV, RGB cast across shoulders, dust-mote light beam from window, 35mm Cinemascope.",
      "Subject mid-stride through a foggy Eastern European train station at dawn, long wool coat, breath visible, low-angle hero shot, ARRI Master Prime 32mm.",
      "Subject framed through a doorway from another room, conversation cut-off, soft incandescent kitchen light pooling around them, voyeuristic mid-distance, 75mm anamorphic.",
      "Subject under a single overhead interrogation lamp, surrounding pure black, sweat beading, jaw tight, hard top light only, large-format monochrome.",
      "Subject riding a motorbike across the salt flats at midday, white sky white ground, helmet off, scarf trailing, drone-style wide-shot lens compression, washed Kodachrome.",
    ],
    defaultAspectRatio: "16:9",
  },
  {
    id: "tech-founder",
    name: "Tech Founder",
    tagline: "Series-A polish",
    description:
      "Boardrooms, podcasts, on-stage keynotes, code-lit faces. Built for press kits and conference deck headers.",
    accentColor: "#5b8def",
    scenes: [
      "Subject mid-keynote on a black stage, single key light from above, audience in soft silhouette, holding a slim wireless mic, shot on Sony Venice 2 with 50mm at f/2.",
      "Subject in a glass-walled boardroom at golden hour, sleeves rolled, mid-gesture explaining a whiteboard diagram, soft window backlight, 35mm.",
      "Subject leaning into a podcast mic in a sound-treated studio, headphones on, warm tungsten key, deep shadow on the off-side, 85mm portrait lens.",
      "Subject reviewing terminal output at a standing desk, RGB monitor glow on face, dark office, nighttime city skyline blur in background, 50mm at f/1.4.",
      "Subject in a knit and chinos against a clean cyclorama, soft beauty-dish key, slight smile, eyes to camera, classic LinkedIn-quality 85mm headshot.",
      "Subject walking through a server room, blue indicator lights striping the face, hand brushing a rack, 24mm wide environmental shot.",
      "Subject seated for a Forbes-style portrait in a leather Eames chair, soft north-window light, hands folded, slight forward lean, medium-format colour neg.",
      "Subject demoing a product to a small huddle of engineers around a laptop, paper cups, tense joy on faces, available-light office, 35mm photojournalism.",
      "Subject in head-to-toe matte black turtleneck against a black backdrop, single hard key from camera-left, austere minimalist tech-icon homage, 100mm macro.",
      "Subject signing paperwork at a marble conference table, sharp suit, golden afternoon backlight through floor-to-ceiling windows, motion of pen, 50mm.",
      "Subject in jeans and tee at a hackathon, energy-drink cans, sticker-covered laptop, fluorescent overhead, candid 28mm reportage with mild flash.",
      "Subject standing in front of a Y-Combinator-style orange wall holding a sharpie and laughing, square 6x6 format, ringlight key, on-axis editorial.",
    ],
    defaultAspectRatio: "4:3",
  },
  {
    id: "editorial",
    name: "Editorial",
    tagline: "Vogue Italia, page seventeen",
    description:
      "High-fashion stylings. Hard light, prop-heavy, oversized silhouettes. Made for portfolios and tear-sheets.",
    accentColor: "#e8b4a0",
    scenes: [
      "Subject in an oversized tailored suit against a seamless cyclorama, hard ringlight key, hands in pockets, asymmetric pose, Vogue Italia April issue.",
      "Subject draped over an antique velvet chaise, single window of north light, oversized pearl earring, eyes closed, large-format 4x5 colour transparency.",
      "Subject submerged to the collarbone in a porcelain bathtub of milk, single overhead softbox, hair slicked back, perfect symmetry, beauty-editorial 100mm macro.",
      "Subject in front of a seven-foot-tall wall of fresh roses, monochrome scarlet wardrobe blending with backdrop, ringlight key, head tilt, 80mm Mamiya.",
      "Subject standing in two feet of sand inside a white-walled gallery, wind machine, dishevelled couture, hard daylight strobe, conceptual editorial 50mm.",
      "Subject seated on a wooden chair in a flooded warehouse, ankle-deep water reflecting them, single industrial pendant lamp, moody editorial 35mm anamorphic.",
      "Subject lying on grass in Marie Antoinette pastel couture, scattered macarons, drone overhead flat-lay, midday sun, hyper-saturated kodachrome.",
      "Subject mid-twirl in a backless emerald gown on a black stage, ring of LED tubes around them, slow-shutter motion blur, 35mm with strobe second-curtain sync.",
      "Subject framed inside a doorway of a brutalist concrete monolith, monochrome charcoal wardrobe, harsh midday top-light, full-body hero shot, 24mm.",
      "Subject behind a sheer organza curtain backlit by a single hard daylight strobe, profile silhouette emerging, breath-on-glass softness, 85mm.",
      "Subject in a translucent latex outfit standing in front of a mirrored wall, soft pink gel uplight, distorted reflections, 50mm conceptual fashion.",
      "Subject up to the waist in a wheat field at dusk, oversized vintage trench coat, single rim of golden hour, painterly composition, Pentax 67 medium-format.",
    ],
    defaultAspectRatio: "3:4",
  },
  {
    id: "streetwear",
    name: "Streetwear",
    tagline: "Off-the-clock heat check",
    description:
      "Tokyo back streets, NYC SoHo, Berlin courtyards. Layered fits, real environments, casual swagger.",
    accentColor: "#222222",
    scenes: [
      "Subject leaning on a graffitied wall in Shibuya at golden hour, hooded windbreaker, layered chains, 35mm street photography Fuji X-Pro look.",
      "Subject mid-crossing a SoHo intersection at lunchtime, oversized denim, taxi blur in background, candid photojournalism 28mm.",
      "Subject sitting on a skate ramp in a Berlin courtyard, sneakers off-frame, brutalist concrete walls, overcast soft light, environmental 24mm wide.",
      "Subject standing under a Hong Kong neon sign at night, puffer jacket, cigarette smoke not visible, ambient mixed-source colour, 50mm cinematic.",
      "Subject crouched in front of a mirror-tile bodega wall at dusk, fully layered fit-check pose, fluorescent sign overhead casting cyan, ringflash for face, 35mm.",
      "Subject mid-jump on a Brooklyn rooftop at sunrise, fitted cap, layered tee plus tech-fleece, motion frozen by strobe, 24mm wide hero shot.",
      "Subject leaning against a vintage Mercedes sedan in a London mews, balaclava optional, fog, drizzle on bodywork, 85mm telephoto compression.",
      "Subject sitting on subway platform bench at 11pm, headphones on, train motion-blurred behind, sodium fluorescents, 35mm grainy reportage.",
      "Subject framed against a Tokyo vending-machine wall, single can in hand, harsh top fluorescents, Fuji 400H Pro film stock, 50mm portrait crop.",
      "Subject jaywalking across a Paris cobblestone street at blue hour, tailored grey wool overcoat, camera caught mid-stride, 35mm street-cinema look.",
      "Subject sitting on the curb beside a graffiti-covered freight container, eating dollar pizza, harsh midday flat sun, 28mm photo-essay framing.",
      "Subject standing in front of a stack of crushed Coke crates in a Mexico City alley, oversized jersey, single overhead bulb, gritty 35mm flash on-camera.",
    ],
    defaultAspectRatio: "4:3",
  },
  {
    id: "travel",
    name: "Travel",
    tagline: "Postcards you can't fake",
    description:
      "Iconic locations, real-world scale, atmospheric weather. Memory pieces from places worth flying to.",
    accentColor: "#f5a623",
    scenes: [
      "Subject on a Greek island clifftop at sunset, white linen, wind-tangled hair, wide drone-style 35mm with telephoto compression, Aegean blue beneath.",
      "Subject standing on the prow of a longtail boat threading limestone karsts in Phang Nga bay at dawn, mist on water, 50mm soft-light portrait.",
      "Subject reading a paperback in a Marrakech riad courtyard, mosaic tile, pomegranate tree dappled shade, mint tea on copper tray, 35mm warm tone.",
      "Subject hiking a basalt ridge in Iceland under low storm clouds, breath visible, bright red shell jacket against grey, 24mm environmental wide.",
      "Subject sitting in the back of a tuk-tuk through neon Bangkok at midnight, motion-blur lights streaking, Fujifilm Pro 400H, 35mm.",
      "Subject swimming in a hidden Mexican cenote, sun shaft piercing the cave water, viewed half-above-half-below the surface, 16mm fisheye, Aquatech housing.",
      "Subject leaning on the rail of a Venetian water taxi at golden hour, pastel buildings receding, 85mm soft portrait, Kodak Ektar.",
      "Subject standing alone on Bolivian salt flats at midday, mirror sky-water reflection, oversized brimmed hat, full-body wide 24mm with deep depth-of-field.",
      "Subject sipping espresso at a Roman cafe table on cobblestone, Vespa parked behind, low afternoon raking light, 50mm Leica candid.",
      "Subject paragliding above the Cappadocia balloon fleet at dawn, harness visible, hot-air balloons polka-dotting valley below, 14mm GoPro POV style.",
      "Subject riding a sleeper-train carriage at first light, condensation on the window, Trans-Siberian wood-panel interior, 35mm available light.",
      "Subject crouched in temple courtyard in Kyoto autumn, maple leaves falling, charcoal kimono, raked-gravel pattern, 85mm telephoto bokeh.",
    ],
    defaultAspectRatio: "16:9",
  },
  {
    id: "dark-academia",
    name: "Dark Academia",
    tagline: "Tweed, candlelight, secret society",
    description:
      "Bodleian libraries, ivy walls, leather-bound stacks. Caravaggio shadows and Latin engravings.",
    accentColor: "#7a5230",
    scenes: [
      "Subject reading by candlelight at a long oak refectory table, Bodleian-style stacks behind, single flame as only light source, 50mm at f/1.4 Caravaggio chiaroscuro.",
      "Subject in tweed and wire-frame glasses on a moss-covered stone bridge, ivy archway, autumn fog, 35mm soft pictorialist look, hand-tinted feel.",
      "Subject sitting cross-legged in a ladder-lined private library, leather chesterfield, hot tea steaming, north window soft light, 35mm Kodak Portra.",
      "Subject mid-stride down a cloister of pointed Gothic arches at dusk, woollen scarf trailing, blue-hour ambient, 24mm wide environmental.",
      "Subject in a cathedral nave looking up at stained-glass rose window, beams of coloured light striping face, full-body wide 28mm large format.",
      "Subject hunched over a spread of antique maps and brass dividers, single green banker's lamp, deep brown shadow elsewhere, 85mm tabletop documentary.",
      "Subject walking ivy-covered college quad in soft snowfall, breath visible, slight smile, navy peacoat, 35mm bokeh portrait.",
      "Subject lecturing from behind a wooden lectern in an empty hall, gestural mid-sentence, dust motes in window beam, monochrome large-format Tri-X.",
      "Subject lying on grass with an open volume of Ovid, fountain in background, dappled cloister sun, overhead 50mm flat-lay portrait.",
      "Subject by a bay window at twilight, vintage globe and barometer on sill, melancholy half-profile, single soft window key, 85mm Rembrandt lighting.",
      "Subject in a candlelit secret-society chamber, brass astrolabe in hand, hood half drawn, single warm taper as key light, 50mm large-format moody.",
      "Subject pacing a chalkboard-covered seminar room, equations behind in white chalk, sleeves rolled, 35mm ambient overhead fluorescents.",
    ],
    defaultAspectRatio: "3:4",
  },
  {
    id: "y2k",
    name: "Y2K",
    tagline: "2003 had heat",
    description:
      "Chrome reflections, frosted plastic, flip-phones, on-camera flash. Sidekick-era nostalgia, glossy.",
    accentColor: "#e8c1ff",
    scenes: [
      "Subject in low-rise jeans and tinted purple sunglasses against a chrome reflective backdrop, direct on-camera flash, 50mm 2003 magazine spread.",
      "Subject seated cross-legged on an inflatable plastic chair in a candy-pink bedroom, flip phone in hand, glittery eyeshadow, 35mm flash photography.",
      "Subject in a velour tracksuit holding a tiny rhinestone dog, mall food court behind, fluorescent ceiling, snapshot 28mm flash on-camera.",
      "Subject leaning against a chrome SUV in a strip-mall parking lot at dusk, frosted-tip hair, oversized white belt, ringflash, late-90s photo-shoot energy.",
      "Subject in a metallic silver puffer crouched on a sidewalk grate, breath visible, MTV-2002 hip-hop video framing, fisheye 16mm.",
      "Subject mid-pose on a backlit transparent acrylic chair, frosted plastic everywhere, hot pink and lime gels, 50mm beauty-editorial flash.",
      "Subject at an arcade DDR machine, motion frozen mid-step, neon screen glow on face, deep arcade darkness behind, 24mm strobe-frozen.",
      "Subject sprawled across a beanbag in front of a CRT TV showing static, glow-in-the-dark stars on ceiling, on-camera bounce flash, 35mm.",
      "Subject in butterfly clips and lip gloss for a passport-photo-style three-shot strip, blue paper backdrop, harsh booth flash, 50mm.",
      "Subject sitting on a yellow Vespa with a very early Sidekick phone, suburban driveway, harsh midday flash, 35mm snapshot.",
      "Subject on a webcam-style square crop, MSN messenger pixel-noise feel, magenta gel rim light, frosted window behind, 85mm.",
      "Subject spinning a translucent yo-yo in a roller rink, disco ball spangles on face, motion-blur skates, 35mm slow-shutter strobe sync.",
    ],
    defaultAspectRatio: "1:1",
  },
  {
    id: "anime-convention",
    name: "Anime Con",
    tagline: "Akihabara at dusk",
    description:
      "Cosplay backdrops, expo crowds, cherry blossoms, neon arcades. Convention floor energy, lovingly composed.",
    accentColor: "#ff6fa3",
    scenes: [
      "Subject under cherry blossoms in Akihabara at dusk, paper lanterns overhead, soft pink ambient, Fujifilm Pro 400H, 50mm shallow depth of field.",
      "Subject inside a neon-soaked Tokyo arcade, mech-game cabinet behind, magenta-cyan reflections on face, 35mm grainy ambient.",
      "Subject mid-pose on a convention-floor staircase, expo banners blurred behind, flash on-camera, 28mm crowd-energy reportage.",
      "Subject framed by a torii gate at twilight, ghibli-soft sky, paper crane in hand, 85mm portrait, dreamy backlight.",
      "Subject sitting on a curb outside the venue eating melon-pan, lanyard heavy with badges, candid 35mm Kodak Gold.",
      "Subject in a maid-cafe interior, pastel pink booth, parfait on table, soft fairy-light bokeh, 50mm at f/1.8.",
      "Subject silhouetted on a rooftop overlook of Shinjuku at night, kanji billboards alive, wind-blown hair, 35mm long exposure with hand-held drag.",
      "Subject browsing a wall of figure-collectibles under harsh fluorescents, fish-eye 8mm wide for the maximalist shelf-scape feel.",
      "Subject riding the Yamanote line late at night, train interior empty, flickering overhead, 35mm tungsten balance with grain.",
      "Subject crouched at street level in Akihabara in the rain, umbrella translucent, signage reflected in puddle, 50mm cinematic anamorphic flare.",
      "Subject on a convention-floor stage holding a microphone, spotlight cone in haze, audience phones glittering, 85mm long lens.",
      "Subject leaning over a glass display case of vintage Famicom cartridges, single LED case-light up-lighting face, macro 100mm shallow focus.",
    ],
    defaultAspectRatio: "3:4",
  },
  {
    id: "album-cover",
    name: "Album Cover",
    tagline: "Type-friendly. Iconic.",
    description:
      "Bold conceptual compositions with negative space for type. Made to print at 12x12 and stop scrolls.",
    accentColor: "#000000",
    scenes: [
      "Subject submerged to the chin in milk, white tile background, overhead fluorescents, perfect axial symmetry, 1:1 square format, ample negative space above.",
      "Subject standing dead-centre in an empty desert, hard midday top-light, white horizon, full-body wide 24mm, type-area sky.",
      "Subject silhouetted against a single column of red gel light in a black room, head turned three-quarter, 50mm minimalist, square crop.",
      "Subject kneeling on white seamless paper, hood up, fully shadowed face, single hard kicker rim only, 85mm conceptual portrait.",
      "Subject's hand emerging from black water holding a single matchstick, rest of frame pure black, 100mm macro, perfect square 1:1.",
      "Subject submerged in a transparent acrylic box of fog, profile only just legible, single side-light, 50mm large-format conceptual.",
      "Subject lying on bare concrete floor flat-lay overhead shot, arms outstretched, single overhead pendant casting hard shadow, 1:1 square.",
      "Subject behind a sheet of cracked safety glass, only one eye visible through a clear pane, hard side-light, 100mm macro.",
      "Subject framed by an oversized vintage paper-cone diffuser, single hot-bulb backlight, monochrome high-key, 50mm large-format.",
      "Subject in a fully red-painted room wearing matching red wardrobe, eyes alone breaking the colour, 85mm beauty editorial.",
      "Subject standing on a roof with helicopter spotlight beam striping them from above, mid-frame, deep blue sky, 35mm ARRI cinematic.",
      "Subject viewed from below on a Plexiglas floor, soles of bare feet pressing the surface, full-body distortion, hard top-light, 14mm.",
    ],
    defaultAspectRatio: "1:1",
  },
  {
    id: "magazine-cover",
    name: "Magazine Cover",
    tagline: "Masthead-ready, eye-contact, tight crop",
    description:
      "Vogue, Time, GQ-style framing. Negative space at the top for masthead, locked eye contact, signature lighting.",
    accentColor: "#c0392b",
    scenes: [
      "Subject head-and-shoulders eye-contact portrait against muted seamless backdrop, soft-box key plus warm rim, generous space above for masthead, 85mm at f/2.",
      "Subject in a tailored turtleneck against deep navy, hard ring-light, jaw set, slight head-tilt, 100mm Vogue-cover crop.",
      "Subject in motion mid-laugh, head thrown slightly back, paper-textured backdrop, beauty-dish key, 85mm energetic candid cover.",
      "Subject wrapped in a chunky knit, oversized collar framing face, pale grey backdrop, north-window soft, 100mm GQ-cover crop.",
      "Subject seated on stool against a blood-red cyclorama, arms folded, direct gaze, hard sun-equivalent strobe, 85mm Time-cover gravitas.",
      "Subject in profile against a textured plaster wall, single Rembrandt key, wisp of hair across cheek, 100mm classic Vanity Fair feel.",
      "Subject wet-look hair, off-shoulder garment, mist of water on skin, blue-grey backdrop, ringlight, 85mm beauty-cover crop.",
      "Subject staring through a sheer black scrim, surreal cover concept, single high-key strobe, 100mm conceptual editorial.",
      "Subject mid-gesture in tailored suit jacket open over bare collarbone, against burnt-orange paper, 85mm power-portrait.",
      "Subject in oversized vintage spectacles, soft beauty light, paper backdrop in pale blush, 100mm intimate cover crop.",
      "Subject framed by a halo of neon tube ring, all face beautifully lit, deep black behind, 85mm contemporary cover style.",
      "Subject in head-to-toe black against black, only face emerging into light, single small key light, 100mm Avedon-homage cover.",
    ],
    defaultAspectRatio: "3:4",
  },
  {
    id: "dating-profile",
    name: "Dating Profile",
    tagline: "Six profile photos that actually swipe",
    description:
      "The cliche-free dating-app set. One of you laughing with a dog, one with a guitar, one cooking, one outdoors. Charming, lived-in, never thirsty.",
    accentColor: "#ff5a5f",
    scenes: [
      "Subject mid-laugh in a sunlit kitchen, holding a wooden spoon over a steaming pot of pasta, herbs on the counter, golden window light, 35mm candid.",
      "Subject sitting cross-legged on a hardwood floor with a golden retriever's head in their lap, paperback book half-open, soft afternoon window, 50mm at f/2.",
      "Subject hiking a mossy Pacific Northwest trail in a flannel shirt, slight smile mid-stride toward the camera, soft overcast diffuse light, 35mm environmental.",
      "Subject playing guitar on a fire escape at dusk, fairy lights on the rail, eyes down on the strings, warm city ambient, 50mm cinematic.",
      "Subject at a farmer's market, holding a paper bag of stone fruit and laughing at something off-camera, candid stranger-portrait energy, 85mm shallow focus.",
      "Subject reading at a corner table of a busy independent bookstore-cafe, espresso and a small notebook, soft tungsten interior light, 35mm photojournalism.",
      "Subject mid-conversation around a backyard dinner table with strung bistro lights, hands in motion, real laugh, candid 35mm at f/2.",
      "Subject paddling a yellow kayak on a glassy lake at sunrise, mist on the water, mountains beyond, environmental wide 24mm, slight back-lit silhouette.",
      "Subject playing pickup basketball in a city park, mid-shot release, sweat, late-afternoon raking sun, telephoto 200mm action freeze.",
      "Subject on a low velvet couch of a small wine bar, glass in hand, laughing at the camera, soft overhead pendant tungsten, 50mm at f/1.8.",
      "Subject crouched at the end of a wooden pier feeding a piece of bread to a duck, golden hour, denim jacket, 35mm candid lifestyle.",
      "Subject leaning on a kitchen island at a friend's house party, holding a beer, half-listening to a story off-frame, ambient warm interior, 35mm reportage.",
    ],
    defaultAspectRatio: "4:3",
  },
];

export function getPack(id: string): Pack | null {
  return PACKS.find((p) => p.id === id) ?? null;
}
